// publicContent.ts — public blog data service (T042).
// Reads ONLY the static tree /data/content/index.json + entries/<publicId>.json
// (generated by scripts/content/build-public-content.mjs). Never touches
// /api/content-studio. Reuses the project fetch boundary (useFetch).
// All validation is fail-closed: unknown fields, wrong types and hash
// mismatches are rejected — a tampered index/entry never renders.
import { ApiError, ApiTimeoutError, useFetch } from '@/composables/useFetch'
import { validateContentDocument } from '@/lib/content/model/document-validator'
import {
  buildContentViewModel,
  RenderValidationError,
  type SafeDocumentViewModel,
} from '@/lib/content/render/contentViewModel'
import type { ContentDocument } from '@/lib/content/model/types'
// Browser-side canonical hash (Web Crypto); node-side generator/checker use the
// equivalent scripts/content/lib/canonical-hash.mjs — a test locks both to
// byte-identical canonicalJson output.
import { entryGenerationHash as computeEntryHash } from '@/lib/content/model/publicHash'

// ---- public contracts (mirror scripts/content/lib/public-content-core.mjs) ----
export const PUBLIC_INDEX_SCHEMA = 'content.index.v1'
export const PUBLIC_ENTRY_SCHEMA = 'content.entry.v1'
const HASH_RE = /^[0-9a-f]{64}$/
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/
const DEFAULT_MEDIA_HOST = 'https://img.nightingalesilence.com/content/'

export interface PublicEntrySummary {
  publicId: number
  title: string
  summary: string | null
  tags: string[]
  publishedAt: string
  revision: number
}

export interface PublicIndex {
  schemaVersion: typeof PUBLIC_INDEX_SCHEMA
  entries: PublicEntrySummary[]
}

export interface PublicMediaRef {
  mediaId: string
  mediaType: string
  publicUrl: string
}

export interface PublicEntry {
  schemaVersion: typeof PUBLIC_ENTRY_SCHEMA
  publicId: number
  title: string
  summary: string | null
  tags: string[]
  publishedAt: string
  revision: number
  generationHash: string
  document: ContentDocument
  media: PublicMediaRef[]
}

export type PublicContentError =
  | { kind: 'network'; message: string }
  | { kind: 'not-found'; publicId: number | null }
  | { kind: 'invalid'; reason: string }
  | { kind: 'empty' }

export const PUBLIC_INDEX_URL = '/data/content/index.json'
export const publicEntryUrl = (publicId: number): string => `/data/content/entries/${publicId}.json`

export function isPositiveIntId(value: string): boolean {
  return /^[1-9]\d*$/.test(value)
}

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return v !== null && typeof v === 'object' && !Array.isArray(v)
}

/** Stable HTTPS CDN URL: exact configured host prefix, no query/credential params. */
function isStableMediaUrl(url: unknown): url is string {
  return typeof url === 'string' && url.startsWith(DEFAULT_MEDIA_HOST) && !url.includes('?')
}

function assertNoExtraFields(obj: Record<string, unknown>, allowed: string[], where: string): void {
  for (const k of Object.keys(obj)) {
    if (!allowed.includes(k)) throw new Error(`${where}: unknown field ${JSON.stringify(k)}`)
  }
}

/** RFC3339 date-time (project contract: format: date-time), e.g. 2026-07-30T00:00:00+00:00. */
const DATE_TIME_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})$/

function isDateTime(value: unknown): value is string {
  return typeof value === 'string' && DATE_TIME_RE.test(value) && !Number.isNaN(Date.parse(value))
}

function validateSummaryEntry(e: unknown, where: string): PublicEntrySummary {
  if (!isPlainObject(e)) throw new Error(`${where} must be a plain object`)
  assertNoExtraFields(e, ['publicId', 'title', 'summary', 'tags', 'publishedAt', 'revision'], where)
  if (typeof e.publicId !== 'number' || !Number.isInteger(e.publicId) || e.publicId < 1) {
    throw new Error(`${where} publicId must be a positive integer`)
  }
  // title: required, non-empty, max 120
  if (typeof e.title !== 'string' || e.title.length === 0) {
    throw new Error(`${where} title must be a non-empty string`)
  }
  if (e.title.length > 120) throw new Error(`${where} title must be at most 120 chars`)
  // summary: field must exist, string or null, max 300
  if (!('summary' in e)) throw new Error(`${where} summary is required`)
  if (e.summary !== null && e.summary !== undefined && typeof e.summary !== 'string') {
    throw new Error(`${where} summary must be a string or null`)
  }
  if (typeof e.summary === 'string' && e.summary.length > 300) {
    throw new Error(`${where} summary must be at most 300 chars`)
  }
  // tags: required array, max 10 items, each 1-30 chars
  if (!Array.isArray(e.tags)) throw new Error(`${where} tags must be an array`)
  if (e.tags.length > 10) throw new Error(`${where} tags must have at most 10 items`)
  for (const t of e.tags) {
    if (typeof t !== 'string' || t.length < 1 || t.length > 30) {
      throw new Error(`${where} tags items must be 1-30 char strings`)
    }
  }
  // publishedAt: strict date-time
  if (!isDateTime(e.publishedAt)) {
    throw new Error(`${where} publishedAt must be a valid RFC3339 date-time`)
  }
  if (typeof e.revision !== 'number' || !Number.isInteger(e.revision) || e.revision < 1) {
    throw new Error(`${where} revision must be a positive integer`)
  }
  return e as unknown as PublicEntrySummary
}

function validateIndex(input: unknown): PublicIndex {
  if (!isPlainObject(input)) throw new Error('index must be a plain object')
  assertNoExtraFields(input, ['schemaVersion', 'entries'], 'index')
  if (input.schemaVersion !== PUBLIC_INDEX_SCHEMA) {
    throw new Error(`index schemaVersion must be ${PUBLIC_INDEX_SCHEMA}`)
  }
  if (!Array.isArray(input.entries)) throw new Error('index.entries must be an array')
  const entries = input.entries.map((e, i) => validateSummaryEntry(e, `index.entries[${i}]`))
  const seen = new Set<number>()
  for (const e of entries) {
    if (seen.has(e.publicId)) throw new Error(`index has duplicate publicId ${e.publicId}`)
    seen.add(e.publicId)
  }
  return { schemaVersion: PUBLIC_INDEX_SCHEMA, entries }
}

function validateMedia(m: unknown, where: string): PublicMediaRef {
  if (!isPlainObject(m)) throw new Error(`${where} must be a plain object`)
  assertNoExtraFields(m, ['mediaId', 'mediaType', 'publicUrl'], where)
  if (typeof m.mediaId !== 'string' || !UUID_RE.test(m.mediaId)) {
    throw new Error(`${where} mediaId must be a UUID`)
  }
  if (typeof m.mediaType !== 'string' || !/^[a-z0-9.+-]+\/[a-z0-9.+-]+$/i.test(m.mediaType)) {
    throw new Error(`${where} mediaType must be a MIME type`)
  }
  if (!isStableMediaUrl(m.publicUrl)) {
    throw new Error(`${where} publicUrl must be a stable HTTPS CDN URL (no query params)`)
  }
  return { mediaId: m.mediaId, mediaType: m.mediaType, publicUrl: m.publicUrl }
}

async function validateEntry(input: unknown, expectedPublicId: number): Promise<PublicEntry> {
  if (!isPlainObject(input)) throw new Error('entry must be a plain object')
  assertNoExtraFields(
    input,
    ['schemaVersion', 'publicId', 'title', 'summary', 'tags', 'publishedAt', 'revision', 'generationHash', 'document', 'media'],
    'entry'
  )
  if (input.schemaVersion !== PUBLIC_ENTRY_SCHEMA) {
    throw new Error(`entry schemaVersion must be ${PUBLIC_ENTRY_SCHEMA}`)
  }
  if (input.publicId !== expectedPublicId) {
    throw new Error(`entry publicId ${JSON.stringify(input.publicId)} does not match requested ${expectedPublicId}`)
  }
  if (typeof input.generationHash !== 'string' || !HASH_RE.test(input.generationHash)) {
    throw new Error('entry generationHash must be a 64-char hex sha256')
  }
  // Fail-closed: the hash must bind the entry's own content.
  if ((await computeEntryHash(input as Record<string, unknown>)) !== input.generationHash) {
    throw new Error('entry generationHash does not match entry content (tampered)')
  }
  const summary = validateSummaryEntry(
    {
      publicId: input.publicId,
      title: input.title,
      summary: input.summary,
      tags: input.tags,
      publishedAt: input.publishedAt,
      revision: input.revision,
    },
    'entry'
  )
  if (!isPlainObject(input.document)) throw new Error('entry requires document')
  if (!Array.isArray(input.media)) throw new Error('entry requires media array')
  const media = input.media.map((m, i) => validateMedia(m, `entry.media[${i}]`))
  // mediaIds referenced by the document must all be present in the media array
  const mediaIds = new Set(media.map((m) => m.mediaId))
  const refs = collectMediaIds(input.document)
  for (const ref of refs) {
    if (!mediaIds.has(ref)) throw new Error(`entry document references unknown mediaId ${ref}`)
  }
  return {
    schemaVersion: PUBLIC_ENTRY_SCHEMA,
    publicId: summary.publicId,
    title: summary.title,
    summary: summary.summary ?? null,
    tags: summary.tags,
    publishedAt: summary.publishedAt,
    revision: summary.revision,
    generationHash: input.generationHash,
    document: input.document as unknown as ContentDocument,
    media,
  }
}

/** Collect every mediaId referenced by image nodes in the document. */
function collectMediaIds(doc: unknown): Set<string> {
  const ids = new Set<string>()
  const walk = (n: unknown): void => {
    if (!n || typeof n !== 'object') return
    const node = n as Record<string, unknown>
    if (node.type === 'image') {
      const attrs = node.attrs as Record<string, unknown> | undefined
      if (typeof attrs?.mediaId === 'string') ids.add(attrs.mediaId)
    }
    if (Array.isArray(node.content)) node.content.forEach(walk)
  }
  const envelope = doc as Record<string, unknown> | undefined
  const rootDoc = envelope?.doc as Record<string, unknown> | undefined
  if (rootDoc && Array.isArray(rootDoc.content)) walk(rootDoc)
  else if (Array.isArray((doc as { content?: unknown[] } | undefined)?.content)) walk(doc)
  return ids
}

/** Convert a validated public entry into the render view model (media:// already
 * resolved by the generator; this layer re-binds mediaId -> publicUrl). */
export function toRenderViewModel(entry: PublicEntry): SafeDocumentViewModel {
  const docCheck = validateContentDocument(entry.document)
  if (!docCheck.valid) {
    const reason = docCheck.errors?.map((e) => e.message).join('; ') ?? 'invalid document'
    throw new RenderValidationError('DOC_INVALID', 'document', reason)
  }
  const mediaById = new Map(entry.media.map((m) => [m.mediaId, m.publicUrl]))
  return buildContentViewModel(entry.document, {
    mediaResolver: (mediaId: string) => mediaById.get(mediaId) ?? null,
  })
}

export function createPublicContentClient() {
  const { api } = useFetch()

  async function fetchPublicIndex(): Promise<PublicIndex> {
    const raw = await api<unknown>(PUBLIC_INDEX_URL, { timeoutMs: 10000 })
    return validateIndex(raw)
  }

  async function fetchPublicEntry(publicId: number): Promise<PublicEntry> {
    const raw = await api<unknown>(publicEntryUrl(publicId), { timeoutMs: 10000 })
    return validateEntry(raw, publicId)
  }
  return { fetchPublicIndex, fetchPublicEntry, toRenderViewModel }
}

export function describePublicContentError(error: unknown): PublicContentError {
  if (error instanceof RenderValidationError) {
    return { kind: 'invalid', reason: error.message }
  }
  if (error instanceof ApiError) {
    if (error.status === 404) return { kind: 'not-found', publicId: null }
    return { kind: 'network', message: error.message }
  }
  if (error instanceof ApiTimeoutError) {
    return { kind: 'network', message: error.message }
  }
  if (error instanceof Error) {
    if (/fetch|network|Failed to fetch/i.test(error.message)) {
      return { kind: 'network', message: error.message }
    }
    return { kind: 'invalid', reason: error.message }
  }
  return { kind: 'invalid', reason: 'unknown error' }
}
